In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [88]:
!pip3 install openpyxl

Requirement already satisfied: openpyxl in c:\users\91882\anaconda3\envs\gemini-langchain-pdf\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\91882\anaconda3\envs\gemini-langchain-pdf\lib\site-packages (from openpyxl) (2.0.0)

In [89]:
df = pd.read_excel('analysis_id.xlsx')

In [90]:
df.head()

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN

In [91]:
df=df[['bidder','bid_range','request_count', 'response_count', 'prebid_win_count','win_count']]
df.head(50)

,bidder,bid_range,request_count,response_count,prebid_win_count,win_count
0,onemobile,0.5-0.6,4,4,1.0,NaN
1,rhythmone,0.3-0.4,3,3,NaN,NaN
2,undertone,0.9-1,1,1,NaN,NaN
3,,,43,0,NaN,NaN
4,rhythmone,0.3-0.4,2,2,NaN,NaN
5,pulsepoint,0.4-0.5,1,1,NaN,NaN
6,,,18,0,NaN,NaN
7,pubmatic,0.2-0.3,3,3,NaN,NaN
8,onemobile,1-1.1,1,1,NaN,NaN
9,onemobile,0.7-0.8,1,1,1.0,NaN
10,pubmatic,0-0.1,1,1,NaN,NaN
11,,,297,0,NaN,NaN
12,,,54,0,NaN,NaN
13,triplelift,0.1-0.2,2,2,NaN,NaN
14,,,18,0,NaN,NaN
15,sharethrough,0.9-1,1,1,1.0,NaN
16,,,14,0,NaN,NaN
17,ix,0.5-0.6,1,1,NaN,NaN
18,sharethrough,1-1.1,1,1,1.0,NaN
19,,,601,0,NaN,NaN
20,medianet,0.2-0.3,1,1,NaN,NaN
21,medianet,7.4-7.5,2,2,2.0,NaN
22,medianet,0.6-0.7,1,1,1.0,NaN
23,medianet,7.2-7.3,2,2,2.0,NaN
24,,,630,0,NaN,NaN
25,medianet,0.8-0.9,6,6,6.0,NaN
26,medianet,0.7-0.8,3,3,3.0,NaN
27,medianet,0.2-0.3,1,1,NaN,NaN
28,onemobile,0.2-0.3,1,1,NaN,NaN
29,,,113,0,NaN,NaN
30,,,13,0,NaN,NaN
31,,,13,0,NaN,NaN
32,,,13,0,NaN,NaN
33,triplelift,0.1-0.2,1,1,1.0,NaN
34,,,16,0,NaN,NaN
35,appnexus,0.5-0.6,5,5,3.0,NaN
36,,,16,0,NaN,NaN
37,triplelift,0.6-0.7,1,1,NaN,NaN
38,appnexus,0.5-0.6,1,1,NaN,NaN
39,ix,1-1.1,2,2,1.0,NaN
40,appnexus,0.5-0.6,7,7,3.0,NaN
41,,,16,0,NaN,NaN
42,ix,0-0.1,1,1,NaN,NaN
43,appnexus,1.3-1.4,2,2,1.0,NaN
44,undertone,1.1-1.2,1,1,NaN,NaN
45,33across,0.2-0.3,3,3,NaN,NaN
46,appnexus,0.8-0.9,2,2,1.0,NaN
47,openx,0.2-0.3,1,1,NaN,NaN
48,pulsepoint,1.2-1.3,2,2,2.0,NaN
49,emx_digital,0.4-0.5,4,4,NaN,NaN

In [92]:
df.describe()

       request_count  response_count  prebid_win_count   win_count
count     5000.00000     5000.000000       1167.000000  186.000000
mean        56.64960        4.304800          2.875750    1.494624
std        632.18282       15.858846          6.852213    1.661153
min          1.00000        0.000000          1.000000    1.000000
25%          1.00000        1.000000          1.000000    1.000000
50%          2.00000        1.000000          1.000000    1.000000
75%         16.00000        2.000000          2.000000    1.000000
max      21855.00000      348.000000        144.000000   16.000000

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bidder            5000 non-null   object
 1   bid_range         5000 non-null   object
 2   request_count     5000 non-null   int64
 3   response_count    5000 non-null   int64
 4   prebid_win_count  1167 non-null   float64
 5   win_count         186 non-null    float64
dtypes: float64(2), int64(2), object(2)
memory usage: 234.5+ KB

In [94]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bid_range',
 'bidder',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prebid_win_count',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'request_count',
 'resample',
 'reset_index',
 'response_count',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'win_count',
 'xs']

In [95]:
#Check for nullls and fill them
df[['win_count','response_count']]=df[['win_count','response_count']].fillna(0)

In [96]:
#calculatte win rate per row
df['win_rate']=df['win_count'] 
df['response_count']
df['win_rate']=df['win_rate'].replace([float('inf'),-float('inf')],0)

In [99]:
#biddar with highest win rate
bidder = df['win_count'].idxmax()
top_rate = df['win_count'].max()
print(f"The bidder with higher win rate is {top_rate} with win count is {bidder}")

The bidder with higher win rate is 16.0 with win count is 2208

In [101]:
df = df[df['bidder'].astype(str).str.strip().astype(bool)]

# ------------------------------
# Top 5 bidders by frequency
top_5_bidders = df['bidder'].value_counts().head(5)
top_5_bidders_df = top_5_bidders.reset_index()
top_5_bidders_df.columns = ['Bidder', 'Count']
print("Top 5 Bidders by Frequency:")
print(top_5_bidders_df)

Top 5 Bidders by Frequency:
      Bidder  Count
0         ix    464
1  onemobile    407
2   medianet    384
3     criteo    306
4   pubmatic    298